### ISSUE TITLE
Blitz Mode | Oils sometimes don't produce money

### ISSUE THREAD

**Issue by Sneer-ra2** [CnCNet/cncnet-yr-client-package#330]
In Blitz Mode, we use oil derricks to get money. An oil has currently these settings:
ProduceCashDelay=35
ProduceCashAmount=30
ProduceCashStartup=10

But sometimes an oil doesn't produce money. It produces the given cash amount of 30 just one time and then stopps giving money. This happens in quickmatch as well as in skirmish games. In skirmish games against the computer, about one out of 200 oils is bugged. It is independent from the game speed. In quickmatch is depends on the connection of the players. It happens more often if lag is involved and it's safe to say that it hits the player with the better connection. There is no other known pattern when this bug occurs.

If it's any kind of help, I can provide videos.

I am willing to pay 100$ bug bounty if this issue gets resolved.

**Comment by Sneer-ra2** [comment]
Raising to 200$ bug bounty.

**Comment by alexp8** [comment]
when the new client with new spawner is rolled out, we can see if the oil bug is still an issue

**Comment by Belonit** [comment]
@Sneer-ra2 Is this issue still exist for the dev branch ?

**Comment by CCCP84** [comment]
I checked a long time ago that in beta was fixed bug that caused the oil derrick to stop generating money after a chrono legionnaire froze its. 
The bug described in this thread will probably also disappear.

**Comment by Sneer-ra2** [comment]
The bug is still present. I wasn't sure for a while, but when you play against certain players, it's as bad as ever.

**Comment by CnCRAZER** [comment]
> The bug is still present. I wasn't sure for a while, but when you play against certain players, it's as bad as ever.

Are we sure this is a legit issue? I haven't seen it happen a single time nor have I seen any evidence of it
